<html xmlns:o='urn:schemas-microsoft-com:office:office' 
      xmlns:w='urn:schemas-microsoft-com:office:word' 
      xmlns='http://www.w3.org/TR/REC-html40'>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{ $title ?? 'Personal Study Notes - Legals Forum' }}</title>
    <!--[if gte mso 9]>
    <xml>
        <w:WordDocument>
            <w:View>Print</w:View>
            <w:Zoom>100</w:Zoom>
            <w:DoNotOptimizeForBrowser/>
        </w:WordDocument>
    </xml>
    <![endif]-->
    <style>
        body {
            font-family: 'Calibri', 'Arial', sans-serif;
            font-size: 11.5pt;
            line-height: 1.5;
            color: #1e293b;
            margin: 20px;
        }
        h1.header-title {
            font-size: 18pt;
            color: #1e3a8a;
            border-bottom: 2pt solid #2563eb;
            padding-bottom: 6pt;
            margin-bottom: 6pt;
        }
        p.header-meta {
            font-size: 9.5pt;
            color: #64748b;
            margin-bottom: 20pt;
        }
        .note-box {
            border: 1pt solid #cbd5e1;
            border-left: 4pt solid #2563eb;
            background-color: #f8fafc;
            padding: 12pt 14pt;
            margin-bottom: 18pt;
        }
        .note-box.yellow { border-left-color: #f59e0b; }
        .note-box.blue { border-left-color: #3b82f6; }
        .note-box.green { border-left-color: #10b981; }
        .note-box.pink { border-left-color: #ec4899; }
        .note-box.purple { border-left-color: #8b5cf6; }

        .badge {
            font-size: 8.5pt;
            font-weight: bold;
            text-transform: uppercase;
            color: #1e40af;
            background-color: #e0e7ff;
            padding: 2pt 6pt;
            display: inline-block;
            margin-bottom: 4pt;
        }
        .doc-title {
            font-size: 13pt;
            font-weight: bold;
            color: #1e40af;
            margin-top: 4pt;
            margin-bottom: 6pt;
        }
        .quote-box {
            background-color: #ffffff;
            border-left: 3pt solid #f59e0b;
            padding: 6pt 10pt;
            margin: 6pt 0 10pt 0;
            font-style: italic;
            color: #475569;
        }
        .note-text {
            font-size: 11.5pt;
            color: #0f172a;
            margin-top: 6pt;
            margin-bottom: 6pt;
        }
        .section-meta {
            font-size: 9.5pt;
            color: #64748b;
            margin-top: 6pt;
        }
        .note-footer {
            border-top: 0.75pt solid #e2e8f0;
            padding-top: 6pt;
            margin-top: 8pt;
            font-size: 9pt;
            color: #94a3b8;
        }
    </style>
</head>
<body>
    <h1 class="header-title">Legals Forum &mdash; Personal Study Notes</h1>
    <p class="header-meta">
        <strong>User:</strong> {{ $user->name ?? 'User' }} &bull; 
        <strong>Export Date:</strong> {{ date('F j, Y, g:i A') }} &bull; 
        <strong>Total Notes:</strong> {{ count($notes) }}
    </p>

    @foreach($notes as $note)
        @php
            $typeClass = $note->document_type;
            if (in_array($typeClass, ['judgment', 'judgement'])) $typeClass = 'case_law';
            $typeLabel = ucwords(str_replace('_', ' ', $typeClass));
            $colorClass = $note->note_color ?? 'blue';
        @endphp
        <div class="note-box {{ $colorClass }}">
            <div class="badge">{{ $typeLabel }}</div>
            <div class="doc-title">{{ html_entity_decode($note->document_title, ENT_QUOTES, 'UTF-8') }}</div>

            @if($note->highlighted_text)
                <div class="quote-box">
                    &ldquo;{{ html_entity_decode($note->highlighted_text, ENT_QUOTES, 'UTF-8') }}&rdquo;
                </div>
            @endif

            <div class="note-text">
                <strong>Note:</strong><br>
                {!! nl2br(e($note->note_content)) !!}
            </div>

            @if($note->article_section)
                <div class="section-meta">
                    <strong>Reference / Court:</strong> {{ html_entity_decode($note->article_section, ENT_QUOTES, 'UTF-8') }}
                </div>
            @endif

            <div class="note-footer">
                Created: {{ $note->created_at->format('M j, Y \a\t g:i A') }}
                @if($note->page_url)
                    &bull; Link: {{ url($note->page_url) }}
                @endif
            </div>
        </div>
    @endforeach

    <div style="margin-top: 30pt; text-align: center; font-size: 9pt; color: #94a3b8; border-top: 0.75pt solid #cbd5e1; padding-top: 8pt;">
        Generated by Legals Forum &bull; All Rights Reserved &copy; {{ date('Y') }}
    </div>
</body>
</html>
