<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('homepage_settings', function (Blueprint $table) {
            $table->id();
            $table->string('key')->unique();
            $table->text('value')->nullable();
            $table->string('label');
            $table->string('type')->default('text'); // text, textarea, boolean
            $table->string('group'); // slide_0, slide_1, slide_2
            $table->timestamps();
        });

        DB::table('homepage_settings')->insert([
            // SLIDE 0 - HOME
            [
                'key' => 'slide_0_published',
                'value' => '1',
                'label' => 'Publish Home Slide',
                'type' => 'boolean',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_badge',
                'value' => 'Cloud-Based Legal Research Platform',
                'label' => 'Badge Text',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_title_part1',
                'value' => "Ghana's Premier",
                'label' => 'Title Part 1 (Regular)',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_title_part2',
                'value' => 'Legal Research',
                'label' => 'Title Part 2 (Gradient highlighted)',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_title_part3',
                'value' => 'Platform',
                'label' => 'Title Part 3 (Regular)',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_description',
                'value' => 'Access thousands of laws, cases, constitutional instruments, and legal news — all in one powerful, searchable platform built for legal professionals.',
                'label' => 'Description Subtitle',
                'type' => 'textarea',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_search_placeholder',
                'value' => 'Search any law, case, or legal document...',
                'label' => 'Search Input Placeholder',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_search_btn',
                'value' => 'Search',
                'label' => 'Search Button Text',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_popular_prefix',
                'value' => 'Popular:',
                'label' => 'Popular Tags Label',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_0_popular_tags',
                'value' => 'Criminal Offences Act, 1992 Constitution, Land Act, Court of Appeal',
                'label' => 'Popular Tags (comma-separated)',
                'type' => 'text',
                'group' => 'slide_0',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SLIDE 1 - WHY CHOOSE US
            [
                'key' => 'slide_1_published',
                'value' => '1',
                'label' => 'Publish Why Choose Us Slide',
                'type' => 'boolean',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Stats Section
            [
                'key' => 'slide_1_stat1_num',
                'value' => '10000',
                'label' => 'Stat 1 Value',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat1_label',
                'value' => 'Laws & Acts',
                'label' => 'Stat 1 Label',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat2_num',
                'value' => '5000',
                'label' => 'Stat 2 Value',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat2_label',
                'value' => 'Case Laws',
                'label' => 'Stat 2 Label',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat3_num',
                'value' => '100',
                'label' => 'Stat 3 Value',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat3_label',
                'value' => 'Constitutions',
                'label' => 'Stat 3 Label',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat4_num',
                'value' => '50000',
                'label' => 'Stat 4 Value',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_stat4_label',
                'value' => 'Registered Users',
                'label' => 'Stat 4 Label',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Browse section
            [
                'key' => 'slide_1_browse_badge',
                'value' => 'EXPLORE',
                'label' => 'Browse Badge Text',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_browse_title',
                'value' => 'Browse Legal Resources',
                'label' => 'Browse Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_browse_desc',
                'value' => "Navigate Ghana's most comprehensive collection of legislation, case law, and constitutional instruments.",
                'label' => 'Browse Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Card 1
            [
                'key' => 'slide_1_card1_title',
                'value' => 'Constitution',
                'label' => 'Card 1 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_card1_desc',
                'value' => 'Read and search the 1992 Constitution of Ghana, its amendments, and historical constitutional documents.',
                'label' => 'Card 1 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Card 2
            [
                'key' => 'slide_1_card2_title',
                'value' => 'Pre-1992 Laws',
                'label' => 'Card 2 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_card2_desc',
                'value' => 'Access ordinances, decrees, and acts passed during previous republics, military regimes, and colonial eras.',
                'label' => 'Card 2 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Card 3
            [
                'key' => 'slide_1_card3_title',
                'value' => 'Post-1992 Laws',
                'label' => 'Card 3 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_card3_desc',
                'value' => 'Browse acts of parliament and subsidiary legislation passed under the Fourth Republic, fully consolidated.',
                'label' => 'Card 3 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Features Header
            [
                'key' => 'slide_1_features_badge',
                'value' => 'Why Choose Us',
                'label' => 'Features Badge Text',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_features_title',
                'value' => 'Built for Legal Professionals',
                'label' => 'Features Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_features_desc',
                'value' => 'Our platform is engineered to streamline your legal research workflow with powerful tools and complete accuracy.',
                'label' => 'Features Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Feature 1
            [
                'key' => 'slide_1_f1_title',
                'value' => 'Precise Search',
                'label' => 'Feature 1 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_f1_desc',
                'value' => 'Find exactly what you need with our advanced search filters and keyword matching system.',
                'label' => 'Feature 1 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Feature 2
            [
                'key' => 'slide_1_f2_title',
                'value' => 'Comprehensive Database',
                'label' => 'Feature 2 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_f2_desc',
                'value' => 'Access one of the largest collections of Ghanaian legislation, from pre-independence ordinances to the latest Acts of Parliament.',
                'label' => 'Feature 2 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Feature 3
            [
                'key' => 'slide_1_f3_title',
                'value' => 'Instant Access',
                'label' => 'Feature 3 Title',
                'type' => 'text',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_1_f3_desc',
                'value' => 'Cloud-based platform available 24/7 from any device. Download, bookmark, and organize your research effortlessly.',
                'label' => 'Feature 3 Description',
                'type' => 'textarea',
                'group' => 'slide_1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SLIDE 2 - STUDENTS PACKAGE
            [
                'key' => 'slide_2_published',
                'value' => '1',
                'label' => 'Publish Students Slide',
                'type' => 'boolean',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_badge',
                'value' => 'For Law Students',
                'label' => 'Badge Text',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_title',
                'value' => 'Empowering the Next Generation of Legal Minds',
                'label' => 'Title',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_desc',
                'value' => 'We provide special discount packages and study tools designed to help law students excel in their academic and professional journeys.',
                'label' => 'Description Subtitle',
                'type' => 'textarea',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bullets
            [
                'key' => 'slide_2_bullet1',
                'value' => 'Discounted premium subscription rates',
                'label' => 'Bullet 1',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_bullet2',
                'value' => 'Access to case briefs, summaries, and exam prep resources',
                'label' => 'Bullet 2',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_bullet3',
                'value' => 'Create personal folders, highlights, and annotations',
                'label' => 'Bullet 3',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_bullet4',
                'value' => 'Collaborate and share research with peers',
                'label' => 'Bullet 4',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_btn_text',
                'value' => 'Claim Student Discount',
                'label' => 'Button Text',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Testimonial quote
            [
                'key' => 'slide_2_quote',
                'value' => 'Legals Forum was an indispensable resource during my studies. The ability to search and bookmark case laws saved me countless hours of research.',
                'label' => 'Testimonial Quote',
                'type' => 'textarea',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_author',
                'value' => 'Ama K.',
                'label' => 'Testimonial Author',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_author_role',
                'value' => 'GSL Graduate & Lawyer',
                'label' => 'Testimonial Author Role',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Testimonial stats
            [
                'key' => 'slide_2_tstat1_num',
                'value' => '98%',
                'label' => 'Testimonial Stat 1 Value',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_tstat1_label',
                'value' => 'Satisfaction Rate',
                'label' => 'Testimonial Stat 1 Label',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_tstat2_num',
                'value' => '10K+',
                'label' => 'Testimonial Stat 2 Value',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_tstat2_label',
                'value' => 'Active Students',
                'label' => 'Testimonial Stat 2 Label',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CTA banner
            [
                'key' => 'slide_2_cta_title',
                'value' => 'Start Your Legal Research Today',
                'label' => 'Bottom CTA Title',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_cta_desc',
                'value' => 'Join thousands of legal professionals, researchers, and students using Legals Forum.',
                'label' => 'Bottom CTA Description',
                'type' => 'textarea',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_cta_btn1_text',
                'value' => 'Create Free Account',
                'label' => 'Bottom CTA Button 1 (Sign Up)',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'slide_2_cta_btn2_text',
                'value' => 'Sign In',
                'label' => 'Bottom CTA Button 2 (Sign In)',
                'type' => 'text',
                'group' => 'slide_2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('homepage_settings');
    }
};
